// do a refactor to be an enum

// AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_AUTO_SIGN_IN = 'AUTH_AUTO_SIGN_IN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const DISMISS_ERROR = 'DISMISS_ERROR';
// CATEGORIES
export const CREATE_CATEGORY_START = 'CREATE_CATEGORY_START';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';
export const LOAD_CATEGORIES_START = 'LOAD_CATEGORIES_START';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_FAIL = 'LOAD_CATEGORIES_FAIL';
// ADMIN
export const CREATE_INCOME_START = 'CREATE_INCOME_START';
export const CREATE_INCOME_SUCCESS = 'CREATE_INCOME_SUCCESS';
export const CREATE_INCOME_FAIL = 'CREATE_INCOME_FAIL';
export const LOAD_INCOME_START = 'LOAD_INCOME_START';
export const LOAD_INCOME_SUCCESS = 'LOAD_INCOME_SUCCESS';
export const LOAD_INCOME_FAIL = 'LOAD_INCOME_FAIL';
// EXPENSES
export const CREATE_EXPENSES_START = 'CREATE_EXPENSES_START';
export const CREATE_EXPENSES_SUCCESS = 'CREATE_EXPENSES_SUCCESS';
export const CREATE_EXPENSES_FAIL = 'CREATE_EXPENSES_FAIL';

