// AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_AUTO_SIGN_IN = 'AUTH_AUTO_SIGN_IN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const DISMISS_ERROR = 'DISMISS_ERROR';
// CATEGORIES
export const CREATE_CATEGORY_START = 'CREATE_CATEGORY_START';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';
