export const Card: string;
export const Fa: string;
export const Primary: string;
export const Accent: string;
export const Info: string;
export const Mini: string;
export const Title: string;
export const Body: string;
export const Footer: string;
